#html odnosno hypertextmarkup lanuage je opisni jezik pomocu kojeg se
 #kreiraju sajtovi tacnije funkcionalnost elemenata jedne web straice,Css(Cascading style sheets) predstavlja jezik koji se
  #koristi za uredijivanje
 #samog izgleda i formatiranje svih elemenata koje vidimo na sajtu
  #HTML je zaduzen za nosenje sadrzaja sajta a CSS taj isti sadrzaj uredjuje
  #CSS su izmislili i specificirali ljudi iz W3C-a,a pojavili su se sa HTML-om 4.0